title: Divyam Bansal # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Frontend Engineer
  <br><br>
  <a href="mailto:divyambansal17@gmail.com">divyambansal17@gmail.com </a>
  <br><br>
  <a href="https://www.linkedin.com/in/divyambansal/">LinkedIn Profile</a>
  <br><br>
  <a href="https://www.gihub.com/divyam1996/">Gihub</a> 
theme: jekyll-theme-minimal
